---
project: 
  type: website
  output-dir: docs

website:
  title: "Graycen Mahon"
  navbar:
    background: primary
    left:
      - href: HomePage.qmd
        text: Home
      - WorkExperience.qmd
      - Writing.qmd
      - AboutMe.qmd
format:
  html:
    theme:
      - mystyles.scss
    mainfont: Serif
    toc: true
    
editor: visual
