---
project: 
  type: website
  output-dir: docs

website:
  title: "Graycen Mahon"
  navbar:
    left:
      - href: HomePage.qmd
        text: Home
      - href: WorkExperience.qmd
        text: Work Experience
      - href: Writing.qmd
        text: Writing Samples
      
format:
  html:
    theme:
      - mystyles.scss
    mainfont: Serif
    toc: true
    
editor: visual
