---
project: 
  type: website
  output-dir: docs

website:
  title: "Graycen Mahon"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - article.qmd
      - Travel.qmd
format:
  html:
    theme:
      - mystyles.scss
    mainfont: Serif
    toc: true
    
editor: visual
