---
project: 
  type: website
  output-dir: docs

website:
  title: "Graycen Mahon"
  navbar:
    background: primary
    left:
      - href: HomePage.qmd
        text: Home
      - href: WorkExperience.qmd
        text: Work Experience
      - href: CommunityInvolvement.qmd
        text: Community Involvement
      - href: Writing.qmd
        text: Writing Samples
      - href: AboutMe.qmd
        text: About Me
      - href: test.qmd
        text: test
      
format:
  html:
    theme:
      - mystyles.scss
    mainfont: Serif
    toc: true
    
editor: visual
