project:
  type: website
  output-dir: docs

website:
  title: "Graycen Mahon"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - article.qmd
format:
  html:
    theme: united
    css: styles.css
    toc: true

editor: visual

