---
title: "Community Involvement"
---

Volunteer/Additional Work Experience
 <li>Attended a work-weekend at a dry farm vineyard in the Cuyama Valley (Condor's Hope Vineyard). Learned about dry farm techniques and drought tolerant plants while participating in weeding and vine pruning</li>
 <li>Member of the Isla Vista branch of the Surfrider organization. Took part in various beach cleanups in Isla Vista, CA</li>
 <li>Experience with tree planting and scalping/weeding tree saplings to ensure survival rate amongst newly planted seeds;
worked a job in West Virginia on a 600 acre farm through Conservation Services out of Waynesboro, VA</li>
 <li>Attended a seminar on permaculture on a farm in Northern Santa Barbara (Gaviota Givings) and
gained knowledge from hands-on activities</li>
 <li>Helped run an event for the Lynchburg, Virginia Historical Society</li>
 <li>Volunteered at a soup kitchen in Lynchburg Virginia. Prepared and distributed meals to the homeless and impoverished community</li>
 <li>Visited and participated in activities at the local nursing home, working with the elderly with and without dementia/alzheimers all throughout elementary, middle school and part of high school</li>
      